DROP TABLE IF EXISTS `PREFIX_menu_block_link`;
DROP TABLE IF EXISTS `PREFIX_menu_item_block`;
DROP TABLE IF EXISTS `PREFIX_menu_link`;
DROP TABLE IF EXISTS `PREFIX_menu_block`;
DROP TABLE IF EXISTS `PREFIX_menu_item`;


